version: '3.3'

services:
 
  kscrape:
    build: kscrape
    depends_on:
      - kscrape_db
    environment:
      POSTGRES_PASSWORD: LKJLKJLKJ

  kscrape_db:
    build: kscrape_db
    environment:
      POSTGRES_PASSWORD: LKJLKJLKJ

  rscrape:
    build: rscrape
    depends_on:
      - kscrape_db
    environment:
      POSTGRES_PASSWORD: LKJLKJLKJ
