version: '3.3'

services:
 
  jscrape:
    build: jscrape
    environment:
      POSTGRES_PASSWORD: LKFO#*)
    volumes:
    - type: bind
      source: ./data
      target: /data

  database:
    build: db
    environment:
      POSTGRES_PASSWORD: LKFO#*)
